name: Docker action Test
description: This is for TEST

inputs:
  name:
    description: call name
    default: "man"

outputs:
  output:
    description: comment to the world

runs:
  using: docker
  image: docker://ubuntu
  args:
    - ${{ inputs.name }}
