name: Test My Custom action

on:
  push:
    branches:
      - main

jobs:
  main-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run my echo-action
        id: custom
        uses: 80-k/echo-action@main
      - name: show output of custom action
        run: echo "${{ steps.custom.outputs }}"
      - name: test3
        run: echo "${{ steps.custom.outputs.to-the-world }}"
